apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-static-website-nginx
  labels:
    app: demo-k8s-static-website-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-k8s-static-website-nginx
  template:
    metadata:
      labels:
        app: demo-k8s-static-website-nginx
    spec:
      containers:
        - name: demo-k8s-static-website-nginx
          image: andylke/demo-k8s-static-website-nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/log/nginx
              name: nginx-log
      volumes:
        - name: nginx-log
          hostPath:
            path: /run/desktop/mnt/host/c/demo-k8s-static-website-nginx
            type: DirectoryOrCreate
