apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-static-website-nginx
  labels:
    app: demo-k8s-static-website-nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: demo-k8s-static-website-nginx
